version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: catalog
    volumes:
        - ./target:/data/
    ports:
        - "27017:27017"
    #command: mongo -u root -p password --eval 'use catalog'
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"